version: '3'
services:

  mysql:
    image: 'mysql:5.7'
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - /mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_USER=coursysuser
      - MYSQL_PASSWORD=coursyspassword
      - MYSQL_DATABASE=coursys
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
